services:
  zrok-enable:
    environment:
      ZROK_ENVIRONMENT_NAME: radial-calendar
  zrok-share:
    restart: no
    environment:
      # this is a dummy value because zrok reserve public requires a backend mode and target, though they're not used
      # when using the SDK
      ZROK_TARGET: http://example.com
      # tell zrok-share.bash to only reserve, but don't run the share, because we're using the SDK to provide the
      # share's bind point
      ZROK_SHARE_RESERVED: "false"
      # authN options
      ZROK_OAUTH_PROVIDER:  # google, github
      ZROK_OATH_EMAILS:     # allow space-separated list of OAuth email addresses or @domain.tld
      ZROK_BASIC_AUTH:      # username:password, mutually-exclusive with ZROK_OAUTH_PROVIDER
  django:
    build: .
    ports: []  # there are no listening ports because the app is hosted by OpenZiti
    environment:
      DJANGO_DEBUG: "False"  # unset or set to "True" to enable debug mode
      DJANGO_SECRET_KEY:
    restart: unless-stopped
    # wait for zrok to reserve a frontend endpoint before starting django
    command: python server.py /mnt
    volumes:
      - zrok_env:/mnt
